### ISSUE TITLE
Onclik "Read More" is triggered even other words are clicked

### ISSUE THREAD

**Issue by DMaendeleo** [webtoon/ReadMoreTextView#41]
Onclik on "Read More" is triggered even when we click on other words, Possible to restrict the click function to word"Read More" Only..?

**Comment by fornewid** [comment]
@MaendelDan
Sorry for late response.
First, thanks for the idea!
We'll consider about the idea you suggested.

Before that, I have one question.
Looking to use it in Jetpack Compose?

**Comment by MaendelDan** [comment]
Thanks,
Yes, I have been using it in Compose Project..

**Comment by fornewid** [comment]
@MaendelDan 
OK, We will consider the jetpack compose module first.

**Comment by fornewid** [comment]
@MaendelDan 
We added 2 slots to ReadMoreText composables on `1.3.4` version. (`onReadMoreClick`, `onReadLessClick`)
Please refer to the following codes:
```diff
    val (expanded, onExpandedChange) = rememberSaveable { mutableStateOf(false) }
    ReadMoreText(
        text = text,
        expanded = expanded,
        modifier = Modifier.fillMaxWidth(),
-       onExpandedChange = onExpandedChange,
        readMoreMaxLines = 2,
        readMoreText = "more",
+       onReadMoreClick = {
+           onExpandedChange(true)
+       },
        readLessText = "less",
+       onReadLessClick = {
+           onExpandedChange(false)
+       },
    )
```

**Comment by fornewid** [comment]
@DMaendeleo
We decided to change the API that supports this feature.

So if you are already using this `onReadMoreClick` and `onReadLessClick` slots,
you need to change your code like this on `1.3.6` version.

Please check the 'Breaking Changes' section in the release note:
https://github.com/webtoon/ReadMoreTextView/releases/tag/v1.3.6-compose
