### ISSUE TITLE
ReadMore is not added when text is in arabic language

### ISSUE THREAD

**Issue by AhmedTawfek** [webtoon/ReadMoreTextView#88]
The text "Read More" is not added
text for test:
البرمجة هي عملية كتابة التعليمات والأوامر لجهاز الكمبيوتر لتنفيذ مهام معينة. تعتبر البرمجة من أهم المهارات في العصر الحديث، حيث تتيح للمبرمجين تطوير تطبيقات وبرامج تساعد في حل المشكلات وتحسين الحياة اليومية. تتطلب البرمجة التفكير المنطقي والإبداع، وتعلم لغات البرمجة المختلفة مثل بايثون وجافا وسي++. يمكن للمبرمجين العمل في مجالات متنوعة مثل تطوير الويب، تطوير التطبيقات، الذكاء الاصطناعي، وتحليل البيانات. البرمجة ليست مجرد كتابة أكواد، بل هي فن يتطلب الصبر والمثابرة. من خلال البرمجة، يمكن تحويل الأفكار إلى واقع ملموس، مما يفتح آفاقًا جديدة للإبداع والابتكار. تعلم البرمجة يمكن أن يكون تحديًا، لكنه يستحق الجهد المبذول، حيث يمكن أن يفتح أبوابًا لفرص مهنية رائعة ومستقبل مشرق.

**Comment by fornewid** [comment]
Thank you for the issue report.
I'll check it out.

**Comment by fornewid** [comment]
I think, you have a trouble when use Jetpack Compose artifacts, right?
I found a problem with counting characters of RTL languages in this library. (=[`TextLayoutResult#getCursorRect()`](https://github.com/webtoon/ReadMoreTextView/blob/main/readmore-foundation/src/main/java/com/webtoonscorp/android/readmore/foundation/BasicReadMoreText.kt#L448C48-L448C61))

I guess it wasn't considered because the services doesn't have RTL.
I have some urgent work to do, so it might take some time to fix it, but I will look into it and fix it.
(until this weekend maybe?)

Thanks for report.

**Comment by fornewid** [comment]
I tried the code you suggested.
However, when considering various cases, the desired result is not always achieved.
For example, when using the `TextDirection` property or when LTR/RTL languages ​​are mixed.

```xml
<string name="description_test">سيدة وصالات طعام عدد \nbلقيام باجتماعات و جميع أنواع الاحتفالات جميع أنواع الاحتفالات</string>
```
```kt
BasicReadMoreText(
    text = stringResource(id = R.string.description_test),
    expanded = false,
    modifier = Modifier.fillMaxWidth(),
    onExpandedChange = {},
    style = TextStyle.Default.copy(
        color = MaterialTheme.colors.onSurface,
        fontSize = 15.sp,
        fontStyle = FontStyle.Normal,
        lineHeight = 22.sp,
        textDirection = TextDirection.Content,
    ),
    readMoreText = stringResource(id = R.string.read_more),
    readMoreMaxLines = 2,
    readLessText = stringResource(id = R.string.read_less),
)
```

It can't be fixed easily.
It looks like we'll need to change most codes handling text.

**Comment by fornewid** [comment]
@AhmedTawfek 
This bug is fixed in [v1.7.1](https://github.com/webtoon/ReadMoreTextView/releases/tag/v1.7.1-compose).

**Comment by fornewid** [comment]
@AhmedTawfek 
Please check if the issue has been fixed in your project.
And if you let me know which version of the library you were trying to use, I'll reflect this patch in that version.
